### ISSUE TITLE
I couldn't able to upload APK into play store using apkup

### ISSUE THREAD

**Issue by aadavvv** [eventOneHQ/apkup#12] opened 2019-11-27 06:34 UTC
`apkup --key /Users/aadav/Downloads/api-4948262631111429462-491123-f930deadbd92.json --track alpha --apk /Users/aadav/AndroidStudioProjects/ABCD/app/release/app-release.apk`
When I try to execute this command, I'm getting the below issue.
`ERROR: Only releases with status draft may be created on draft app.`

It works fine, when I use **playup** for uploading 
`playup -a /Users/aadav/Downloads/api-4948262631111429462-491123-f930deadbd92.json -t beta /Users/aadav/AndroidStudioProjects/ABCD/app/release/app-release.apk`

**Comment by nprail** [comment] 2019-11-27 11:41
Interesting. Have you uploaded any APKs to this particular app yet? Does your app have any draft releases?

Also, can you try uploading again after setting the following environment variable:
```
export DEBUG=apkup:*
```
Then send the log (be sure to redact any sensitive info).

**Comment by aadavvv** [comment] 2019-11-28 15:32
`$ apkup --key /Users/aadav/Downloads/api-4948262631111429462-491123-f930deadbd92.json --track alpha --apk /Users/aadav/AndroidStudioProjects/ABCD/app/release/app-release.apk
⠋ Uploading APK...  apkup:helpers > Parsing manifest +0ms
  apkup:helpers > Detected package name com.uob.abcd +19ms
  apkup:helpers > Detected version code 13 +1ms
  apkup:Edit > Authenticating +0ms
⠙ Uploading APK...  apkup:Edit > Authenticated successfully +96ms
  apkup:Edit > Creating edit +1ms
⠙ Uploading APK...  apkup:Edit > Created edit with id 04941293865047230491 +809ms
  apkup:Upload > Uploading release +0ms
⠇ Uploading APK...  apkup:Upload > Uploaded /Users/aadav/AndroidStudioProjects/ABCD/app/release/app-release.apk with version code 13 and SHA1 2349485d4903f9ecc9daa880ee8b784520c7592d +2s
  apkup:Upload > Assigning APK to alpha track +1ms
⠴ Uploading APK...  apkup:Upload > Assigned APK to alpha track +615ms
  apkup:Edit > Commiting changes +3s
ERROR: Only releases with status draft may be created on draft app.`

**Comment by nprail** [comment] 2019-11-28 18:19
Does your app have any draft releases currently?

**Comment by nprail** [comment] 2019-12-11 15:43
@aadavvv Any updates on this issue? Is this a new app that hasn't ever had a production release?

**Comment by sravan1000** [comment] 2019-12-17 13:12
it is saying forbidden for me can anyone help?

**Comment by sravan1000** [comment] 2019-12-17 13:20
error stack:

"Error: Forbidden
    at Gaxios._request (/home/sravan/data/publish-play/node_modules/gaxios/build/src/gaxios.js:85:23)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async JWT.requestAsync (/home/sravan/data/publish-play/node_modules/apkup/node_modules/google-auth-library/build/src/auth/oauth2client.js:346:18)"

**Comment by nprail** [comment] 2019-12-17 14:13
@sravan1000 Please create a new issue for that. It looks unrelated to this one :)

**Comment by nprail** [comment] 2020-03-11 12:51
Closing this since I can't reproduce it and haven't received a response. Feel free to re-open the issue with more details 🙂

**Closed by nprail** 2020-03-11 12:51 UTC
Labels: bug, question
